### ISSUE TITLE
Change the email in the code of conduct

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/GitHubCity#130]
There is an email in the file https://github.com/iblancasa/GitHubCity/blob/master/CODE_OF_CONDUCT.md. We should remove it

**Comment by tunnelsnake** [comment]
I can tackle this project. Should the email be changed or should the phrase be removed all together?

**Comment by iblancasa** [comment]
@tunnelsnake I would prefer to have it removed. Thank you!

**Comment by tunnelsnake** [comment]
#132 All set!

**Comment by iblancasa** [comment]
Thank you!
