### ISSUE TITLE
Add a logo

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/GitHubCity#138]

**Comment by vaibhav1729** [comment]
What type of logo you wanted @iblancasa

**Comment by iblancasa** [comment]
I think would be nice to have something simple and easy to vectorize

**Comment by allisonsampaio** [comment]
let me help

**Comment by iblancasa** [comment]
@allisonsampaio ok :D

**Comment by Guillergood** [comment]
![posible_logo_final](https://user-images.githubusercontent.com/16701917/31864669-9f1b0e6c-b761-11e7-9808-24261c3042a2.png)

**Comment by iblancasa** [comment]
:+1:

**Comment by JLeneau** [comment]
👍
