### ISSUE TITLE
The location is not checked

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/GitHubCity#159]
The locations is not filtered now.

**Comment by iblancasa** [comment]
This was detected here https://github.com/iblancasa/GitHubSpanishRankingGenerator/issues/18

**Comment by JJ** [comment]
I had to filter these by hand, in many cases. Also by excluding some regexes.

**Comment by iblancasa** [comment]
I was doing the filter. When I refactored the code, I forget to add the location to the user's profile.
I am testing the fix now.
