### ISSUE TITLE
Implementation details

### ISSUE THREAD

**Issue by pwaqo** [iblancasa/GitHubCity#91]
I dont't really understand why are you using the BeautifulSoup library if Github provides a [rich API](https://developer.github.com/v3/) to access (I think) all the data you need.

Couldn't this be made easier with the great [github3.py](https://github.com/sigmavirus24/github3.py) library?

**Comment by iblancasa** [comment]
I need it because there are some information that is not provided by de API. This information is only provided by the web

**Comment by pwaqo** [comment]
https://developer.github.com/v3/repos/statistics/

**Comment by iblancasa** [comment]
Yes but I don't take information about the repos. I take information about the users. The GitHub API does not provide, for example, the number of contributions
